# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='original_run_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
