# Generated by Django 2.2.17 on 2021-02-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtask',
            name='repeat',
            field=models.BigIntegerField(default=0, help_text='minute = 60; hourly = 3600; daily = 86400; weekly = 604800; 2 weeks = 1209600; 4 weeks = 2419200'),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat',
            field=models.BigIntegerField(default=0, help_text='minute = 60; hourly = 3600; daily = 86400; weekly = 604800; 2 weeks = 1209600; 4 weeks = 2419200'),
        ),
    ]
