# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_units',
            field=models.CharField(choices=[(b'seconds', b'Seconds'), (b'minutes', b'Minutes'), (b'hours', b'Hours'), (b'days', b'Days'), (b'weeks', b'Weeks'), (b'months', b'Months'), (b'years', b'Years')], default=b'seconds', max_length=256),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='repeat_units',
            field=models.CharField(choices=[(b'seconds', b'Seconds'), (b'minutes', b'Minutes'), (b'hours', b'Hours'), (b'days', b'Days'), (b'weeks', b'Weeks'), (b'months', b'Months'), (b'years', b'Years')], default=b'seconds', max_length=256),
        ),
    ]
